
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'Shougo/vimshell'
#{ 'rev': '3787e5' }

[[plugins]]
repo = 'Shougo/deoplete.nvim'		# 補完
[[plugins]]
repo = 'zchee/deoplete-go'			# golang
[[plugins]]
repo = 'landaire/deoplete-swift'	# swift
[[plugins]]
repo = 'zchee/deoplete-clang'		# C/C++/Obj-C/Obj-C++ 
[[plugins]]
repo = 'carlitux/deoplete-ternjs'	# javascript
[[plugins]]
repo = 'Shougo/deoplete-rct'		# ruby
[[plugins]]
repo = 'poppyschmo/deoplete-latex'	# latex
[[plugins]]
repo = 'neomake/neomake'			# 外部コマンドを非同期実行
[[plugins]]
repo = 'rking/ag.vim'				# 行末ホワイトスペース削除
[[plugins]]
repo = 'mattn/emmet-vim'			# html,css,xml support
[[plugins]]
repo = 'LeafCage/yankround.vim'		# クリップボード拡張
[[plugins]]
repo = 'fatih/vim-go'				# golang support

# colorscheme {{{

#[[plugins]]
#repo = 'AlessandroYorba/Alduin'			# 

[[plugins]]
repo = 'flazz/vim-colorschemes'		# カラースキーマいっぱい
[[plugins]]
repo = 'romainl/Apprentice'			# 
[[plugins]]
repo = 'jacoborus/tender.vim'		# 
[[plugins]]
repo = 'reedes/vim-colors-pencil'	# 
[[plugins]]
repo = 'freeo/vim-kalisi'			# 
[[plugins]]
repo = 'Haron-Prime/Antares'			# 
[[plugins]]
repo = 'bluz71/vim-moonfly-colors'			# 
[[plugins]]
repo = 'NewProggie/NewProggie-Color-Scheme'			# 
[[plugins]]
repo = 'zcodes/vim-colors-basic'			# 
[[plugins]]
repo = 'ayu-theme/ayu-vim'			# 
[[plugins]]
repo = 'dracula/vim'			# 
[[plugins]]
repo = 'fcpg/vim-fahrenheit'			# 
[[plugins]]
repo = 'joshdick/onedark.vim'			# 
[[plugins]]
repo = 'Donearm/Ubaryd'			# 
[[plugins]]
repo = 'jyota/vimColors'			# 
[[plugins]]
repo = 'DrSpatula/vim-buddy'			# 
[[plugins]]
repo = 'evgenyzinoviev/vim-vendetta'			# 
[[plugins]]
repo = 'hewo/vim-colorscheme-deepsea'			# 
[[plugins]]
repo = 'croaker/mustang-vim'			# 
[[plugins]]
repo = 'vim-scripts/inkpot'			# 
[[plugins]]
repo = 'lxmzhv/vim'			# 
[[plugins]]
repo = 'goatslacker/mango.vim'			# 
[[plugins]]
repo = 'jpo/vim-railscasts-theme'		# 
[[plugins]]
repo = 'justincampbell/vim-railscasts'		# 
[[plugins]]
repo = 'zeis/vim-kolor'			# 
[[plugins]]
repo = 'ninja/sky'			# 
[[plugins]]
repo = 'tomasr/molokai'				# molokai

# }}}
