" 2017/07/16/16:28.48 edited.
" 2017/07/15/17:30.13 edited.
" 2017/05/10/08:27.50 edited.

" よくある設定 {{{
if &compatible
	set nocompatible               " Be iMproved
endif

set noreadonly
set autoread
set encoding=utf-8
set fileencoding=utf-8
set noautoindent
set nosmartindent
set cindent
set tabstop=4
set shiftwidth=4
set title
set showmatch
set display=lastline
set showmatch
set matchtime=1
"set clipboard=unnamed
set clipboard+=unnamed
set smartcase
"set wrap
set nowrap
set number
set ruler
set list
set listchars=tab:>-,trail:>,nbsp:%,extends:>,precedes:<,eol:<
set backspace=indent,eol,start	" バックスペースで各種消せるようにする
set incsearch
set hlsearch
set whichwrap=h,l
set nowrapscan
"set ignorecase
set noignorecase	" 大文字小文字を区別する
set hidden
set history=2000
set noexpandtab
set helplang=en
set matchpairs& matchpairs+=<:> "対応括弧に<と>のペアを追加
set foldmethod=marker
cmap w!! w !sudo tee > /dev/null %  "w!!でrootとして保存

if has('win32unix') && &term =~# '^xterm' && &t_Co < 256
  set t_Co=256  " Extend cygwin terminal color
endif

augroup swapchoice-readonly
  autocmd!
  autocmd SwapExists * let v:swapchoice = 'o'
augroup END

if has('win32unix')
  let &t_ti .= "\e[1 q"
  let &t_SI .= "\e[5 q"
  let &t_EI .= "\e[1 q"
  let &t_te .= "\e[0 q"
endif


"色設定
hi SpecialKey ctermfg=237 guifg=#3a3a3a
hi NonText ctermfg=66 guifg=#5f8787

if (exists('+colorcolumn'))		" 80カラムを強調
	set colorcolumn=80
	highlight ColorColumn ctermbg=9
endif

"}}}

" dein.vim {{{

" NeoBundle時代の古い記述
" いるのかわからない
augroup vimrc-checktime
  autocmd!
  autocmd WinEnter * checktime
augroup END

" dein のインストール方法
" 他のプラグインとは違うインストールディレクトリを決めて以下のコマンドを実行
" $ curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
" $ sh ./installer.sh {specify the installation directory}

"dein Scripts-----------------------------

set runtimepath+=$HOME/.config/vim/dein/repos/github.com/Shougo/dein.vim	" dein.vimのインストールディレクトリ

if dein#load_state($HOME . '/.config/vim/dein')
	call dein#begin($HOME . '/.config/vim/dein')

	" Let dein manage dein  Required:
	call dein#add($HOME . '/.config/vim/dein/repos/github.com/Shougo/dein.vim')

	call dein#add('Shougo/neosnippet.vim')
	call dein#add('Shougo/neosnippet-snippets')

	" toml
	let g:rc_dir		= expand("~/.config/vim")
	let s:toml		= g:rc_dir . '/dein.toml'
	let s:lazy_toml	= g:rc_dir . '/dein_lazy.toml'

	" read toml and cache
	call dein#load_toml(s:toml,			{'lazy':0})
	call dein#load_toml(s:lazy_toml,	{'lazy':0})

	call dein#end()
	call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

if dein#check_install()
	call dein#install()
endif

"End dein Scripts-------------------------

" }}}

" キー割り当て変更 {{{
"キー割り当て変更コマンドは、下のように、モードごと、再割当(remap)の有無によって別の名前が割り当てられています。
"再割当無し	再割当有り	モード
"noremap		map		ノーマルモード＋ビジュアルモード
"noremap!	map!	コマンドラインモード＋インサートモード
"nnoremap	nmap	ノーマルモード
"vnoremap	vmap	ビジュアル(選択)モード
"cnoremap	cmap	コマンドラインモード
"inoremap	imap	インサート(挿入)モード

" ウィンドウ間の移動
nnoremap swj <C-w>j
nnoremap swk <C-w>k
nnoremap swl <C-w>l
nnoremap swh <C-w>h
" ウィンドウ自体の移動
nnoremap swJ <C-w>J
nnoremap swK <C-w>K
nnoremap swL <C-w>L
nnoremap swH <C-w>H		" ウィンドウを左に移動を
nnoremap swe <C-w>=		" ウィンドウの大きさを揃える


nnoremap ; :
nnoremap : ;
noremap - $
inoremap jj <Esc>						" 入力モード中に素早くJJと入力した場合はESCとみなす
nmap <Esc><Esc> :nohlsearch<CR><Esc>	" ESC連打でハイライト解除

nnoremap s4t :%s/\s\s\s\s/\t/g<CR>		" スペース4をタブに置換
nnoremap s2t :%s/\s\s/\t/g<CR>			" スペース4をタブに置換

nnoremap <CR> o<ESC>

nnoremap Q <Nop>						" exモードを無効
nnoremap Q q
nnoremap q <Nop>

nnoremap setv :e $HOME/.vimrc<CR><ESC>	" setv でvimrcを開く
nnoremap setb :e $HOME/.bashrc<CR><ESC>

nnoremap vs :<C-u>VimShell<CR><ESC>
nnoremap vp :<C-u>VimShellPop<CR><ESC>

autocmd BufRead,BufNewFile *.py setfiletype python
autocmd FileType python setl inoremap # <ESC>0i#<ESC>wi

"nnoremap <TAB>f :<C-u>VimFilerBufferDir -split -simple -winwidth=35 -no-quit -toggle<CR>

nnoremap <TAB>t :<C-u>tabnew<CR><ESC>	" TAB-tに新規タブ作成を割り当て
nnoremap <TAB>n gt						" 次のタブに移動
nnoremap <TAB>p gT						" 前のタブに移動
nnoremap <TAB>w <C-w>w					" TABwにウィンドウ切り替えを割り当て

nnoremap <TAB>dt a<C-r>=strftime("%Y/%m/%d/%H:%M")<CR><ESC>		" 日時挿入
nnoremap <Space>dt gg0O# <C-r>=strftime("%Y/%m/%d/%H:%M.%S")<CR> edited.<ESC>0		" 日時挿入

" }}}

colorscheme molokai
"colorscheme deepsea

