[[plugins]]
repo = 'Shougo/denite.nvim'

# colorscheme {{{

#[[plugins]]
#repo = 'AlessandroYorba/Alduin'	# 

[[plugins]]
repo = 'flazz/vim-colorschemes'		# カラースキーマいっぱい
[[plugins]]
repo = 'romainl/Apprentice'			# 
[[plugins]]
repo = 'jacoborus/tender.vim'		# 
[[plugins]]
repo = 'reedes/vim-colors-pencil'	# 
[[plugins]]
repo = 'freeo/vim-kalisi'			# 
[[plugins]]
repo = 'Haron-Prime/Antares'		# 
[[plugins]]
repo = 'bluz71/vim-moonfly-colors'	# 
[[plugins]]
repo = 'NewProggie/NewProggie-Color-Scheme'			# 
[[plugins]]
repo = 'zcodes/vim-colors-basic'	# 
[[plugins]]
repo = 'ayu-theme/ayu-vim'			# 
[[plugins]]
repo = 'dracula/vim'				# 
[[plugins]]
repo = 'fcpg/vim-fahrenheit'		# 
[[plugins]]
repo = 'joshdick/onedark.vim'		# 
[[plugins]]
repo = 'Donearm/Ubaryd'				# 
[[plugins]]
repo = 'jyota/vimColors'			# 
[[plugins]]
repo = 'DrSpatula/vim-buddy'		# 
[[plugins]]
repo = 'evgenyzinoviev/vim-vendetta'	# 
[[plugins]]
repo = 'hewo/vim-colorscheme-deepsea'	# 
[[plugins]]
repo = 'croaker/mustang-vim'		# 
[[plugins]]
repo = 'vim-scripts/inkpot'			# 
[[plugins]]
repo = 'lxmzhv/vim'					# 
[[plugins]]
repo = 'goatslacker/mango.vim'		# 
[[plugins]]
repo = 'jpo/vim-railscasts-theme'	# 
[[plugins]]
repo = 'justincampbell/vim-railscasts'	# 
[[plugins]]
repo = 'zeis/vim-kolor'				# 
[[plugins]]
repo = 'ninja/sky'					# 
[[plugins]]
repo = 'tomasr/molokai'				# molokai

# }}}


